PACKAGE_NAME="axs-touch"
PACKAGE_VERSION="1.0.git20260403"
MAKE[0]="make all KDIR=${kernel_source_dir}"
CLEAN="make clean KDIR=${kernel_source_dir}"
BUILT_MODULE_NAME[0]="axs_touch"
DEST_MODULE_LOCATION[0]="/kernel/drivers/input/touchscreen"
AUTOINSTALL="yes"
